### ISSUE TITLE
server doesn't start

### ISSUE THREAD

**Issue by rudyv** [Shinao/SmartMirror#3]
Hi, great project!
when I try to run it the "node server.js" command i get an error like this:

`pi@raspberrypi3:~/SmartMirror $ node server.js

/home/pi/SmartMirror/motion.js:34
                fs.access("public/" + req.params.filepath, fs.R_OK | fs.W_OK, (err) => {
                                                                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/SmartMirror/server.js:19:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`

Can you help me out with this ?
Thanks
Rudy

**Comment by Shinao** [comment]
Hello,

You probably have an older version of Node.js (<4.x) that does not support arrow function : => {} instead of function() {}.
I don't think I used it a lot in my project, it may be the only time, change the  `(err) =>` to `function(err)` and if it works I will commit the changes.

You could also update Node.js to a more recent version.
