### ISSUE TITLE
i am getting this error

### ISSUE THREAD

**Issue by Arvrairobo** [Shinao/SmartMirror#8]
i am using logitech USB camera on ubuntu desktop (not on raspberry pi)

and i am getting this error

python test.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "test.py", line 85, in ManageMotion
    gesture = motion.GetGesture()
  File "/home/js6/Documents/SmartMirror/Motion/motion.py", line 192, in GetGesture
    self.TryToTrackHand()
  File "/home/js6/Documents/SmartMirror/Motion/motion.py", line 116, in TryToTrackHand
    foundPalm = search_hand.SearchPalmFromMask(search_hand_mask)
  File "/home/js6/Documents/SmartMirror/Motion/gesture.py", line 134, in SearchPalmFromMask
    if self.InitFromMask(search_hand_mask):
  File "/home/js6/Documents/SmartMirror/Motion/gesture.py", line 101, in InitFromMask
    (_, contours, _) = cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack

any head start will be a great..

thank you for the great script

**Comment by Shinao** [comment]
Your OpenCV version seems to be different than mine, you probably don't have to change it but you still have to modify some function calls like findContours. Find the documentation of your OpenCV version and modify when necessary.
